name: Reusable defectdojo security gate workflow

on:
  workflow_call:
    inputs:
      defectdojo_product_name:
        required: true
        type: string
        description: DefectDojo product name
      defectdojo_threshold_total:
        required: false
        type: number
        default: 1000000
        description: DefectDojo total findinds threshold
      defectdojo_threshold_critical:
        required: false
        type: number
        default: 0
        description: DefectDojo critical findinds threshold
      defectdojo_threshold_high:
        required: false
        type: number
        default: 0
        description: DefectDojo high findinds threshold
      defectdojo_threshold_medium:
        required: false
        type: number
        default: 1000000
        description: DefectDojo medium findinds threshold
      defectdojo_threshold_low:
        required: false
        type: number
        default: 1000000
        description: DefectDojo low findinds threshold
      defectdojo_threshold_info:
        required: false
        type: number
        default: 1000000
        description: DefectDojo info findinds threshold
    secrets:
      defectdojo_host:
        required: true
        description: DefectDojo URL (MUST PUT SLASH AT THE END) eg. https://demo.defectdojo.org/
      defectdojo_username:
        required: true
        description: DefectDojo Username
      defectdojo_password:
        required: true
        description: DefectDojo Password

jobs:
  security-gate:
    runs-on: ubuntu-latest
    steps:
      - name: DefectDojo Security Gate Thresholds
        uses: portswigger-cloud/defectdojo-findings-thresholds@v1
        with:
          defectdojo-url: ${{ secrets.defectdojo_host }}
          defectdojo-username: ${{ secrets.defectdojo_username }}
          defectdojo-password: ${{ secrets.defectdojo_password }}
          defectdojo-product: ${{ inputs.defectdojo_product_name }}
          # Need to put every thresholds to make it working
          total-threshold: ${{ inputs.defectdojo_threshold_total }}
          critical-threshold: ${{ inputs.defectdojo_threshold_critical }}
          high-threshold: ${{ inputs.defectdojo_threshold_high }}
          medium-threshold: ${{ inputs.defectdojo_threshold_medium }}
          low-threshold: ${{ inputs.defectdojo_threshold_low }}
          info-threshold: ${{ inputs.defectdojo_threshold_info }}
